language: php

php:
  - 7.4
  - 8.0

matrix:
  fast_finish: true

  include:
    - php: 8.0
      env: COVERAGE=1

before_script:
  - composer self-update
  - composer update

script:
  - if [[ $PHPCS != '1' && $COVERAGE != '1' ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs --standard=psr2 --ignore=*vendor*,*src/views* ./; fi
  - if [[ $COVERAGE = 1 ]]; then vendor/bin/phpunit --coverage-clover=clover.xml; fi

after_success:
  - if [[ $COVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
